### ISSUE TITLE
AsyncTerminator not public like SyncTerminator

### ISSUE THREAD

**Issue by lberezy** [wolf4ood/gremlin-rs#122]
Is there a reason why `AsyncTerminator` isn't publicly accessible in the same way that `SyncTerminator` is, and if not could it be added?

I'm happy to send a PR (it's a one line addition of `pub use remote::AsyncTerminator;` to `src/aio/process/traversal/mod.rs`) if required.

This makes it very difficult to pass around a `GraphTraversalSource<_>` when using async.

Additionally, it could be useful to have a trait that both the `AsyncTerminator` and `SyncTerminator` to ease the case of writing code that can deal with either type easily.

**Comment by wolf4ood** [comment]
Hi @lberezy , 

No reason, it should be public. 
Yes if you can send a PR :)
Thanks
