### ISSUE TITLE
Update installation steps on README.md file

### ISSUE THREAD

**Issue by augmented-fog** [wolf4ood/gremlin-rs#168]
The README.md file currently references:

- version `0.4.0`, but latest version is `0.8.2`
- that the package name is `gremlin_client`, but it is now `gremlin-client`

**Comment by wolf4ood** [comment]
Thanks @augmented-fog 

I've just pushed a fix

**Comment by augmented-fog** [comment]
Oh wow, that was fix. Thank you so much.
