### ISSUE TITLE
Generic Error Message Not Included In Message

### ISSUE THREAD

**Issue by criminosis** [wolf4ood/gremlin-rs#203]
@wolf4ood would it be possible to include the wrapped error message in the thiserror annotation for the [Generic Error](https://github.com/wolf4ood/gremlin-rs/blob/42a4050c0d15f1b93511ade858b864d0e0e7739c/gremlin-client/src/error.rs#L11-L12)?

I think it'd just need to be changed to something like:

```
#[error("data store disconnected: {0}")]
Generic(String),
```

As it stands I keep having this error occur and `data store disconnected` gets logged, but I don't have any context as to why.

Sort of tangental to the issue but is it expected for when this error occurs to drop the client and manually re-create it? Currently I just keep retrying the same traversal, but once whatever error this is starts to happen it seems to keep failing in my retry loop until I restart the program.

**Comment by wolf4ood** [comment]
Hi @criminosis sure, can you provide a PR for this?

**Comment by criminosis** [comment]
@wolf4ood happily. Pushed it up https://github.com/wolf4ood/gremlin-rs/pull/204

If you wouldn't mind cutting a release once it's merged I'd appreciate it!

**Comment by wolf4ood** [comment]
Sure i can do the release :)

**Comment by criminosis** [comment]
Thank you!

**Comment by wolf4ood** [comment]
@criminosis released :)

**Comment by criminosis** [comment]
@wolf4ood Thanks!
