### ISSUE TITLE
Project state and contributing

### ISSUE THREAD

**Issue by jdemilledt** [wolf4ood/gremlin-rs#26]
This project seems to be either unmaintained or low priority. I have a need for Gremlin in my current project, so this library would be useful if further developed. Would I be able to get access so I can fix the current open issues, and fix any further?

**Comment by wolf4ood** [comment]
Hi @jdemilledt 

thanks for being interested to the project. I would not call it unmaintained, the last release has been done recently with experimental support for GLV  :) 

I work on this project mostly on my free time, so external contribution are very welcome and also feedback :)

 Which are the feature that you need the most for your project?

**Comment by jdemilledt** [comment]
Async is a want, SSL and auth are required. I'm willing to contribute code to get these done.

**Comment by wolf4ood** [comment]
@jdemilledt 

that would be great :).

Async it will take more time since things are changing and stabilizing in async Rust.
But SSL and auth should be relatively easy to implement
