### ISSUE TITLE
Any chance to implement TextP?

### ISSUE THREAD

**Issue by jdeepee** [wolf4ood/gremlin-rs#31]
Would be great if TextP was implemented as to bring the library close to being in-line with the current gremlin documentation. I will try to put together the start to the implementation and make  PR - might need some help however as I don't fully understand the code base yet.

Cheers

**Comment by wolf4ood** [comment]
Hi @jdeepee 

sure, i will work on this ASAP :)

**Comment by jdeepee** [comment]
Implemented in #42
