### ISSUE TITLE
Support for GraphSONv2

### ISSUE THREAD

**Issue by jeffrey-howard** [wolf4ood/gremlin-rs#62]
I'm working on a Rust project that could benefit from using Azure Cosmos DB under its graph database mode of operation, with a Gremlin API.  I've been looking at gremlin-rs to use as the client library, but it appears that Cosmos DB only supports GraphSONv2, and gremlin-rs is only GraphSONv3.

I believe I have successfully added GraphSONv2 support, without breaking the existing v3 code. I'm new to GraphSON, but all the test are passing, which seems a good sign.

Would support for GraphSONv2 be a helpful contribution to this project?  If so, I'd be happy to open a pull request and work through any comments/feedback to get the change into good enough shape to merge.

**Comment by wolf4ood** [comment]
Hi @jeffrey-howard 

yes i believe it would be helpful. If you have something working please submit the PR :)

Thanks
