### ISSUE TITLE
Missing 'coalesce' from builder/traversal.

### ISSUE THREAD

**Issue by gzp-crey** [wolf4ood/gremlin-rs#67]
I really like the builder/traversal pattern where the query is generated by rust function and not from string)
Unfortunately I'm missing the 'coalesce' function.

I'm trying to map the following expression:
```
client.execute(
                r#"g.V().has('role','name',role).fold()
                    .coalesce(
                        unfold(),
                        addV('role')
                    .property('name',role))"#,
                &[("role", &role)],
            )
            .await?;
```

Thanks

**Comment by wolf4ood** [comment]
Hi @gzp-crey 

yes it's still  missing. I should have some time to work on this for the next release.

Thanks

**Comment by wolf4ood** [comment]
Hi @gzp-crey 

i've just merged the coalesce step. I've attached a test case which is similar to the above traversal .You can find it here 

https://github.com/wolf4ood/gremlin-rs/blob/master/gremlin-client/tests/integration_traversal.rs#L1782

Let me know if it make sense to you 
Thanks
