### ISSUE TITLE
Convert bytecode into query string

### ISSUE THREAD

**Issue by gzp-crey** [wolf4ood/gremlin-rs#68]
It'd be great if the builder could emit querystrings and not just bytecode.
Azure Cosmos DB does not support 'bytecode' and this way the "fluent" api is not compatible to it.
I know it's a lack of the Azure Cosmos DB (and they have an open ticket of this for at least 2 years), but i'd be very happy if a ByteCode::to_string would exists.

Thanks.

**Comment by wolf4ood** [comment]
Hi @gzp-crey 

thanks for reporting this. I'm aware of the limitation of Cosmos DB. I also saw the open ticket.
For now i think i don't have the bandwidth to implement this. I'm also not sure it will be a trivial task .

I'd say let's wait a bit more for the bytecode support.

**Comment by gzp-crey** [comment]
Ok, well than let's close the ticket.
