### ISSUE TITLE
ConnectionStream does not handle pong messages

### ISSUE THREAD

**Issue by gzp-crey** [wolf4ood/gremlin-rs#69]
When connected to cosmos DB it sometimes sends a Pong message.
This message triggers an unimplemented branch in ConnectionStream::recv.

**Comment by gzp-crey** [comment]
I've tried to send it back as a Ping and return an empty vector, but unfortunately it did not work and may require some modification the way recv is used (had no time to investigate it)

```
Message::Pong(e) => {
                self.0.send(Message::Ping(e)).await.map_err(GremlinError::from)?;
                Ok(Vec::default())
            }
````

**Comment by wolf4ood** [comment]
@gzp-crey 

Thanks for raising this, let me check.

**Comment by wolf4ood** [comment]
Hi @gzp-crey 

i've pushed a fix. It will be available in the next release

Thanks
