### ISSUE TITLE
Serialization of Boolean Value

### ISSUE THREAD

**Issue by maldrake** [wolf4ood/gremlin-rs#97]
Hi,

I seem to be running into a problem using a boolean value in a query.  I think I've paired it down to a minimal example, as follows: 

```
use gremlin_client::{ConnectionOptions, GraphSON, GremlinClient, TlsOptions, ToGValue};

fn main() {
    let client = GremlinClient::connect(
        ConnectionOptions::builder()
            .host("127.0.0.1")
            .port(8182)
            .pool_size(4)
            .ssl(true)
            .tls_options(TlsOptions {
                accept_invalid_certs: true,
            })
            .serializer(GraphSON::V3)
            .deserializer(GraphSON::V3)
            .credentials("stephen", "password")
            .build(),
    )
    .expect("Expected client");

    let mut param_list: Vec<(&str, &dyn ToGValue)> = Vec::new();
    param_list.push(("prop_1", &true));

    let r0 = client.execute(
        "g.addV('Example').property('propname', prop_1).project('props').by(valueMap())",
        param_list.as_slice(),
    );
    println!("r0 -- {:#?}", r0);
}
```

If I change `&true` to a different type, such as an integer constant, floating point constant, or reference to a `String`, everything works as expected. The query is sent to the Tinkerpop server, executed, and the results returned.

Am I missing something in how I'm constructing the query and parameters, or does it look like there may really be a bug here?

**Comment by wolf4ood** [comment]
Hi @maldrake 

thanks for raising this issue and the reproducer. Let me check on it 
Which error do you get?

**Comment by maldrake** [comment]
Oh, sorry about that. I'd meant to include the output from the `println!` of the result at the end.  It is:

```
R0 -- Err(
    Json(
        "serde_json::Value::String",
    ),
)
```
